import { readFileSync } from 'node:fs';
export const products = JSON.parse(readFileSync('data/products.json', 'utf8'));
const icon = readFileSync('assets/mark-original.svg', 'utf8').match(/<path d="([^"]+)"/)[1];
const template = readFileSync('index.html', 'utf8');
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function productPath(product, color = product.colors[0]) {
  return `/products/${product.id}/${color.id === 'graphite' ? '' : `${color.id}/`}`;
}
function brand() { return `<svg viewBox="0 0 252 293" aria-hidden="true"><path d="${icon}"/></svg>`; }
function textileMark(id, placement, color, productId) {
  if (!placement) return '';
  const width = placement.glyphWidth * 252 / 178;
  const knit = productId === 'beanie';
  const pitch = knit ? 140 : 75;
  const threads = [-25,25,90].map((angle,i) => `<pattern id="thread-${id}-${i}" width="${pitch}" height="${pitch}" patternUnits="userSpaceOnUse" patternTransform="rotate(${angle})"><image href="/assets/materials/thread-${color}.webp" width="${pitch}" height="${pitch}" preserveAspectRatio="xMidYMid slice"/></pattern>`).join('');
  const surface = `<rect x="0" y="65" width="126" height="228" fill="url(#thread-${id}-0)"/><rect x="126" y="65" width="126" height="228" fill="url(#thread-${id}-1)"/><rect x="0" y="0" width="252" height="65" fill="url(#thread-${id}-2)"/>`;
  const strength = color === 'midnight-navy' ? 9 : 6;
  const relief = knit ? `<filter id="relief-${id}" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="${.2126*strength} ${.7152*strength} ${.0722*strength} 0 -.82 ${.2126*strength} ${.7152*strength} ${.0722*strength} 0 -.82 ${.2126*strength} ${.7152*strength} ${.0722*strength} 0 -.82 0 0 0 1 0"/></filter>` : '';
  const mobile = placement.mobile ? `--mobile-x:${placement.mobile.x}%;--mobile-y:${placement.mobile.y}%;--mobile-width:${placement.mobile.glyphWidth*252/178}%;` : '';
  return `<svg class="garment-mark" viewBox="0 0 252 293" aria-hidden="true" data-original-mark="true" data-finish="thread" data-knit-contact="${knit}" style="--mark-x:${placement.x}%;--mark-y:${placement.y}%;--mark-width:${width}%;--mark-angle:${placement.angle || 0}deg;${mobile}"><defs><clipPath id="shape-${id}"><path data-icon-path="original" d="${icon}"/></clipPath>${threads}${relief}</defs><g ${knit ? `filter="url(#relief-${id})"` : ''} clip-path="url(#shape-${id})">${surface}</g></svg>`;
}
export function imageFrame({product, color, view, placements, eager = false, id = '', href}) {
  const file = view === 'collection' ? product.collection : color[view];
  const alt = view === 'collection' ? product.collectionAlt : `Generated design concept: ${product.name} in ${color.name}, ${view === 'front' ? 'complete front view' : 'close view of the tonal original icon and material'}.`;
  const placement = placements?.[product.id]?.[color.id]?.[view];
  const [w,h] = view === 'collection' ? [1536,1024] : [1122,1402];
  const frame = `<span class="image-frame" data-view="${view}" style="aspect-ratio:${w}/${h}" ${id ? `id="${id}"` : ''}><img src="/assets/products/${file}" width="${w}" height="${h}" alt="${escape(alt)}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">${textileMark(id || `${product.id}-${color.id}-${view}`, placement, color.id, product.id)}</span>`;
  return href === null ? frame : `<a class="image-link" href="${href || productPath(product, color)}" aria-label="${escape(view === 'collection' ? `Explore ${product.name} in ${color.name}` : `Inspect ${product.name} in ${color.name} — ${view === 'front' ? 'detail' : 'front'} view`)}">${frame}</a>`;
}
function access(product, color, preview) {
  const context = product ? `${product.name} / ${color.name}` : 'Collection I';
  return `<section class="access" id="access" aria-labelledby="access-title"><div class="access-grid wrap"><div><p class="eyebrow">By request</p><h2 id="access-title">Private Access</h2><p class="lead">Tell us which piece caught your eye.</p><p class="access-context" id="accessContext">${escape(context)}</p></div><div class="access-form"><form id="suForm" data-preview="${preview}"><input type="hidden" name="piece" id="inquiryPiece" value="${escape(product?.name || 'Collection I')}"><input type="hidden" name="color" id="inquiryColor" value="${escape(color?.name || 'Not selected')}"><label for="email">Email address</label><div class="form-row"><input id="email" type="email" name="email" placeholder="you@example.com" autocomplete="email" required aria-describedby="form-note suOk"><button type="submit">Request access</button></div><p class="form-note" id="form-note">${preview ? 'Preview mode: test this form without sending a request.' : 'Your request includes the piece and color shown above.'}</p></form><p class="status" id="suOk" role="status" aria-live="polite"></p><noscript><p class="form-note">For inquiries, email <a href="mailto:inquiries@valdovieri.com?subject=${encodeURIComponent(`VALDOVIERI inquiry — ${context}`)}">inquiries@valdovieri.com</a>.</p></noscript></div></div></section>`;
}
function layout({title, description, content, preload, product, color, preview}) {
  const header = `<header class="top"><nav class="nav wrap" aria-label="Main navigation"><a class="brand" href="/" aria-label="VALDOVIERI home">${brand()}<span>VALDOVIERI</span></a><div class="nav-links"><a href="/#collection">Collection I</a><a href="#access">Private Access</a></div></nav></header>`;
  const footer = `<footer><div class="wrap"><div class="footer-row"><span class="footer-name">VALDOVIERI</span><span>Collection I</span><a href="mailto:inquiries@valdovieri.com">inquiries@valdovieri.com</a><a href="#top">Back to top ↑</a></div><p class="provenance">All garment images show generated design concepts with digitally applied original marks. Colors and construction are proposed. Materials, dimensions, origin, manufacture and availability remain unconfirmed.</p></div></footer>`;
  const routeScript = product ? `<script type="application/json" id="colorRoutes">${JSON.stringify(Object.fromEntries(product.colors.map(c => [c.id,productPath(product,c)])))}</script><script src="/color-route.js"></script>` : '';
  const values = {COLOR_ROUTE:routeScript, TITLE:escape(title), DESCRIPTION:escape(description), HEADER:header, CONTENT:content + access(product,color,preview), FOOTER:footer, PRELOAD:`<link rel="preload" as="image" href="/assets/products/${preload}" fetchpriority="high">`};
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => values[key]);
}
export function renderCollection(placements, preview = true) {
  const jacket = products[0], graphite = jacket.colors[0];
  const hero = `<section class="hero wrap" aria-labelledby="collection-title"><h1 class="wordmark">VALDOVIERI</h1><div class="hero-grid">${imageFrame({product:jacket,color:graphite,view:'collection',placements,eager:true})}<div class="hero-copy"><p class="eyebrow">Collection I / A new study</p><h2 id="collection-title">Form.<br> Texture.<br> Restraint.</h2><p>Three considered shapes.<br>Graphite, Soft Gray and Midnight Navy.</p><a class="text-link" href="${productPath(jacket)}">Explore The Jacket <span aria-hidden="true">↗</span></a><p class="caption">The Jacket / Graphite<br>Generated design concept</p></div></div></section>`;
  const cards = products.map(p => `<article class="piece-card">${imageFrame({product:p,color:p.colors[0],view:'front',placements})}<div class="piece-card-heading"><p class="eyebrow">${p.number} / ${p.type}</p><h3><a href="${productPath(p)}">${p.name}</a></h3></div><p>${escape(p.description)}</p><div class="card-colors" aria-label="Proposed colors for ${p.name}">${p.colors.map(c => `<a href="${productPath(p,c)}"><span class="swatch-dot" style="--swatch:${c.hex}" aria-hidden="true"></span>${c.name}</a>`).join('')}</div><a class="text-link" href="${productPath(p)}">Explore the piece <span aria-hidden="true">↗</span></a></article>`).join('');
  const collection = `<section class="collection wrap" id="collection" aria-labelledby="pieces-title"><div class="section-head"><div><p class="eyebrow">01 — 03 / The pieces</p><h2 id="pieces-title">Considered, individually.</h2></div><p>Each piece has two proposed colors.<br>Explore the shape and the details.</p></div><div class="piece-grid">${cards}</div></section>`;
  const studies = `<section class="editorial"><div class="wrap"><div class="section-head"><div><p class="eyebrow">A closer study</p><h2>Quiet by design.</h2></div><p>Headwear, with a discreet tonal mark.</p></div><div class="editorial-grid">${products.slice(1).map(p => {const c=p.colors.find(c=>c.id===p.collectionColor)||p.colors[0];return `<figure>${imageFrame({product:p,color:c,view:'collection',placements})}<figcaption><a class="text-link" href="${productPath(p,c)}">${p.name} / ${c.name} <span aria-hidden="true">↗</span></a><p class="caption">Generated design concept</p></figcaption></figure>`;}).join('')}</div></div></section>`;
  return layout({title:'VALDOVIERI — Collection I',description:'VALDOVIERI. Three considered shapes in Graphite, Soft Gray and Midnight Navy.',content:hero+collection+studies,preload:jacket.collection,preview});
}
export function renderProduct(product, color, placements, preview = true) {
  const swatches = product.colors.map(c => `<a class="color-option" href="${productPath(product,c)}" data-color="${c.id}" aria-current="${c.id === color.id}"><span class="swatch-dot" style="--swatch:${c.hex}" aria-hidden="true"></span><span>${c.name}</span></a>`).join('');
  const content = `<div class="product-wrap wrap" data-product="${product.id}"><a class="back-link" href="/#collection">← Collection I</a><section class="product-grid" aria-labelledby="product-title"><div class="product-gallery" id="gallery">${imageFrame({product,color,view:'front',placements,eager:true,href:`${productPath(product,color)}#detail`})}<p class="caption" data-image-caption>${product.name} / ${color.name} / Front view</p></div><div class="product-copy"><p class="eyebrow">Collection I / ${product.number}</p><h1 id="product-title">${product.name}</h1><p class="product-lead">${escape(product.description)}</p><fieldset class="color-selector"><legend>Proposed color — <strong id="selectedColor">${color.name}</strong></legend><div class="color-options">${swatches}</div></fieldset><a class="primary-link" href="#access" id="pieceAccess">Request Private Access <span aria-hidden="true">↘</span></a><a class="inquiry-link" id="pieceInquiry" href="mailto:inquiries@valdovieri.com?subject=${encodeURIComponent(`VALDOVIERI inquiry — ${product.name} / ${color.name}`)}">Inquire about ${product.name} / <span data-inquiry-color>${color.name}</span> ↗</a><p class="concept-note">Design concept. Final materials, dimensions and availability are to be confirmed.</p></div></section><section class="detail-grid" id="detail" aria-labelledby="detail-title"><div>${imageFrame({product,color,view:'detail',placements,href:`${productPath(product,color)}#gallery`})}<p class="caption" data-image-caption>${product.name} / ${color.name} / Detail view</p><button type="button" class="detail-zoom" id="openDetail" hidden>Inspect detail at full resolution ↗</button></div><div class="detail-copy"><p class="eyebrow">The detail</p><h2 id="detail-title">A quieter signature.</h2><p>${escape(product.details)}</p><p class="placement-note">${escape(product.placement)} Dimensions are design proposals, not sample measurements.</p><a class="text-link" href="#gallery">Back to the complete view <span aria-hidden="true">↑</span></a></div></section></div>`;
  const zoom = `<dialog id="detailDialog" aria-labelledby="zoomTitle"><div class="zoom-header"><h2 id="zoomTitle">${product.name} / ${color.name}</h2><button type="button" id="closeDetail">Close ×</button></div><p class="zoom-note">Concept detail at its original resolution. Scroll to inspect the material.</p><div class="zoom-viewport" id="zoomViewport">${imageFrame({product,color,view:'detail',placements,id:'zoomDetailImage',href:null})}</div></dialog>`;
  return layout({title:`${product.name} — ${color.name} — VALDOVIERI`,description:`${product.name}, a VALDOVIERI design concept in ${product.colors.map(c=>c.name).join(' and ')}.`,content:content+zoom,preload:color.front,product,color,preview});
}
